spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ['*']
            allowedMethods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allowedHeaders: ['*']

      routes:
        - id: customer-transaction-loan-service
          uri: lb://customer-transaction-loan-service
          predicates:
            - Path=/api/customers/**,/api/loans/**,/api/transactions/**
        - id: bank-employee-service
          uri: lb://bank-employee-service
          predicates:
            - Path=/bank-employee/**
        - id: bankmanager-admin-service
          uri: lb://bankmanager-admin-service
          predicates:
            - Path=/admin/**,/api/bankmanager/**
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/